Function Get-EWFCategoryPermissions{
    param
    (
    [String]
    [Parameter(Mandatory)]
    $WFGUID,
    
    [String]
    [Parameter(Mandatory)]
    $WFID,

    [String]
    [Parameter(Mandatory)]
    $SQLInstance
    )
    Invoke-TestReportsFolder
    $categoryPivot = Invoke-EWFCategoryQuery -WFGUID $WFGUID -WFID $wfid -SQLInstance $SQLInstance
    $html = $categoryPivot | Out-HtmlView -Title "Category Permissions" -AutoSize -PagingLength 100 -Filtering -FilteringLocation Bottom -PreContent {"<h2>Permissions generated by Workflow ID $wfid</h2>"} -FilePath $foldername\CategoryPermissions.$guid.html -PreventShowHTML

}
