Function Get-EWFQueuePermissions{
    param
    (
    [String]
    [Parameter(Mandatory)]
    $WFGUID,
    
    [String]
    [Parameter(Mandatory)]
    $WFID,

    [String]
    [Parameter(Mandatory)]
    $SQLInstance
    )
    Invoke-TestReportsFolder
    $queuePivot = Invoke-EWFQueueQuery -WFGUID $guid -WFID $wfid -SQLInstance $SQLInstance
    $html = $queuePivot | Out-HtmlView -Title "Queue Permissions" -AutoSize -PagingLength 100 -Filtering -FilteringLocation Bottom -PreContent {"<h2>Permissions generated by Workflow ID $wfid</h2>"} -FilePath $foldername\QueuePermissions.$guid.html -PreventShowHTML

}