Function Get-EWFInstitutionPermissions{
    param
    (
    [String]
    [Parameter(Mandatory)]
    $WFGUID,
    
    [String]
    [Parameter(Mandatory)]
    $WFID,

    [String]
    [Parameter(Mandatory)]
    $SQLInstance
    )
    Invoke-TestReportsFolder
    $foldername = "C:\inetpub\wwwroot\Reports"
    $institutionPivot = Invoke-EWFInstitutionQuery -WFGUID $WFGUID -WFID $wfid -SQLInstance $SQLInstance
    $html = $institutionPivot | Out-HtmlView -Title "Insitution Permissions" -AutoSize -PagingLength 100 -Filtering -FilteringLocation Bottom -PreContent {"<h2>Permissions generated by Workflow ID $wfid</h2>"} -FilePath $foldername\InstitutionPermissions.$guid.html -PreventShowHTML

}
