# DO NOT MODIFY THIS FILE!
# THIS FILE WAS AUTOGENERATED BY ISESTEROIDS AND WILL BE OVERWRITTEN WHEN YOU EXPORT FUNCTIONS TO THIS MODULE.

# USE THIS FILE FOR ADDITIONAL MODULE CODE. THIS FILE WILL NOT BE OVERWRITTEN
# WHEN NEW CONTENT IS PUBLISHED TO THIS MODULE:
. $PSScriptRoot\init.ps1


# LOADING ALL FUNCTION DEFINITIONS:

. $PSScriptRoot\Get-EWFCategoryPermissions.ps1
. $PSScriptRoot\Get-EWFInstitutionPermissions.ps1
. $PSScriptRoot\Get-EWFQueuePermissions.ps1
. $PSScriptRoot\Get-EWFReportUrl.ps1
. $PSScriptRoot\Invoke-EWFCategoryQuery.ps1
. $PSScriptRoot\Invoke-EWFInstitutionQuery.ps1
. $PSScriptRoot\Invoke-EWFQueueQuery.ps1
. $PSScriptRoot\Invoke-TestReportsFolder.ps1
